GET http://localhost:5000/api/customers
Authorization:Bearer CfDJ8Kr98FAGjclEnyST6RDljqrIt_bo2vgYxqN-MEjqDP_tU-DubxqiKbr0eouI3HtxFvT7Ht-CeNd_bMPDh1ILYONIbeKYwT2qWpGyWSWpqbWx7HIAli1NOSxOjNwyHaDUbBSFWmgf9BdCPp0tV0styu1obQFZqdvWX_WI5Lt-9_fH7A6R8e6jdwKCHdh56xrYoKgSnpg5sliOJWAxmspgjwgc_7GPymfFlt8UaHi4x_JF8cZ8dEp1ZhB6xsMAmbW64-1FkizQ-odmzJ2YeAKNCcOwkmscaokZ_PTt0R8QG9NchRXr0sB0YehkxhH1j_MDM-EjzmLXbYhwc2EXZ4Ni4-A9sRSlPyXKyNwWvSM8SKhvAOaUaZHo2p4czlZzUdB-bs_R4DYXVAZl7CSPIC-oDdQKn1l82Qt4u2tzjEjrqt3UTaqFt9xGnRWgzR79HO6uslFh2x_z8sVhuAi3GMfNoUqLp1Futmo6m-7wkNwJmY4GKlUmUlEZikRByd0hM_qM7VyV1ctyiYQtE8Z4fADUtN3YleuAQkRSXNL9VKTCIhsvh3ftPZ9DoKzYHxWrGq7-U7lCn7_kXCNURL42gbRV4p21YdMaFy0nKB6HfnERDpI79zPF6MIs6NcNrAxLASqHd0EOPRWx5bVFhN5wAUvLKpniuO5dO__IfSocAmVeyf_Jh9o-L0ntt3I7h_xUCAM3JX91bdImtcDLANOingcbSnM


GET http://localhost:5000/api/customers?withAddresses=true

### 
GET http://localhost:5000/api/customers/3

###
GET http://localhost:5000/api/timebills/9
Authorization:Bearer CfDJ8Kr98FAGjclEnyST6RDljqrIt_bo2vgYxqN-MEjqDP_tU-DubxqiKbr0eouI3HtxFvT7Ht-CeNd_bMPDh1ILYONIbeKYwT2qWpGyWSWpqbWx7HIAli1NOSxOjNwyHaDUbBSFWmgf9BdCPp0tV0styu1obQFZqdvWX_WI5Lt-9_fH7A6R8e6jdwKCHdh56xrYoKgSnpg5sliOJWAxmspgjwgc_7GPymfFlt8UaHi4x_JF8cZ8dEp1ZhB6xsMAmbW64-1FkizQ-odmzJ2YeAKNCcOwkmscaokZ_PTt0R8QG9NchRXr0sB0YehkxhH1j_MDM-EjzmLXbYhwc2EXZ4Ni4-A9sRSlPyXKyNwWvSM8SKhvAOaUaZHo2p4czlZzUdB-bs_R4DYXVAZl7CSPIC-oDdQKn1l82Qt4u2tzjEjrqt3UTaqFt9xGnRWgzR79HO6uslFh2x_z8sVhuAi3GMfNoUqLp1Futmo6m-7wkNwJmY4GKlUmUlEZikRByd0hM_qM7VyV1ctyiYQtE8Z4fADUtN3YleuAQkRSXNL9VKTCIhsvh3ftPZ9DoKzYHxWrGq7-U7lCn7_kXCNURL42gbRV4p21YdMaFy0nKB6HfnERDpI79zPF6MIs6NcNrAxLASqHd0EOPRWx5bVFhN5wAUvLKpniuO5dO__IfSocAmVeyf_Jh9o-L0ntt3I7h_xUCAM3JX91bdImtcDLANOingcbSnM

###
POST http://localhost:5000/api/timebills
Content-Type: application/json
Authorization:Bearer CfDJ8Kr98FAGjclEnyST6RDljqp2vSzpfPs1MtQ4jsjV-Yxk7sDT65d7MnsCLhu-IWYc-_sHHxps0PMUBljbN_3gC6FkOAid6vzFotomPHXu6Z6A2V2dPDAfSuJ1DR_r51KSWI8bi09ERX0ujbcbAZCSL3jQSsRGm1RFc1hnlSVm0n11GINL3-4aMC5vQalpdQQsDVRXGqYtidciDueSfWQf_KsSmg0Ao8ufyHYVYF0XPgXCKfq_1KbVGyoLnmerUgTY2-UVdmLzbGaQKvOntl9OCLI35eXroSIuiEGsclsy8utwGKoc4Cd5-I2Cuf2CaXBRm49pmE0xBCCkRg7J48gTDkk9bGqQ8aDcx5Sw4kkoO9RABfDaFxB6fIk6t2t4mIAhZv3c4Zxo7pXoOGwTKtsMgEqmKls3WovwHspUtd3oVHa_g6r-3pz9h5J0TJ6RKVkOlPdLJlsucy89hdUQ_jEhxb4IfPgizh3j4trKIyg50RYZaYoKxDNdEGvECGBAT8Bcipg5EQ122Zy3LC4z5AHCh6S89-OXjuCJIc4QOG-n5RQlZYoLLJ3Y9YtPycTqr3nlUJMDZ_HdTB-qUb12ku1UaavKdmwssi2-6FemeqPl4Mlj4etuKRodef5NoYpQXU8pdEWsdcv9kiJNhsCTH_5rcJlQXaRboqWoVX5qSkVXh7wZz3pv07P8lkU27Irup2wQ3gmCXFMNrbbQmuHOgtQU420
{
  "hoursWorked": 3.0,
  "rate": 200,
  "date": "2024-05-05",
  "work": "I did................",
  "customerId": 2,
  "employeeId": 2
}

### 
GET http://localhost:5000/api/customers/2/timebills

### 
GET http://localhost:5000/api/customers/2/timebills/5

### 
POST http://localhost:5000/api/customers/2/timebills/5

### 
POST http://localhost:5000/api/auth/login
Content-type: application/json
{
  "email": "chenlejun@gmail.com",
    "password": "6iwJs_8_AX*Q8pa"

}
