GET http://localhost:5000/api/customers

### 

GET http://localhost:5000/api/customers?withAddresses=true

### 
GET http://localhost:5000/api/customers/3

###
GET http://localhost:5000/api/timebills/9


###
POST http://localhost:5000/api/timebills
Content-Type: application/json

{
  "hours": 3.0,
  "billingRate": 225.00,
  "date": "2024-05-05",
  "workPerformed": "I did a thing...",
  "customerId": 2,
  "employeeId": 2
}

### 
GET http://localhost:5000/api/customers/1/timebills

### 
GET http://localhost:5000/api/customers/1/timebills/10


